### ISSUE TITLE
Hi Jason,I have a question about type chinese

### ISSUE THREAD

**Issue by Jackxun123** [JasonWibbo/HabboSwfOpenSource#1]
In habbo-hotel，I use Habbo.swf from [ragezone](http://forum.ragezone.com/f353/swf-source-code-production-201611291003-a-1161735/index3.html)
 I can't type chinese and can't display chinese ,too.
How can I fix it?
Thank you!

![picture1](https://sa-os-1251840830.cos.ap-beijing.myqcloud.com/seafile/20200223211420.png)

![picture1-1](https://sa-os-1251840830.cos.ap-beijing.myqcloud.com/seafile/20200223211745.png)

![picture2](https://sa-os-1251840830.cos.ap-beijing.myqcloud.com/seafile/20200223211550.png)

![picture2-2](https://sa-os-1251840830.cos.ap-beijing.myqcloud.com/seafile/20200223211809.png)

**Comment by JasonWibbo** [comment]
You need to change the fonts : https://github.com/JasonWibbo/HabboSwfOpenSource/tree/master/src/fonts with

**Comment by Jackxun123** [comment]
Thank you!

**Comment by Jackxun123** [comment]
Thank you!
And it also will solve the "can't typing chinese"?

**Comment by JasonWibbo** [comment]
Yes just have to replace the fonts with font chinese

**Comment by Jackxun123** [comment]
> Yes just have to replace the fonts with font chinese

OK,copy that

**Comment by Jackxun123** [comment]
> Yes just have to replace the fonts with font chinese
